version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
  service:
    image: anshemonaev/fsi:latest
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/example_db
      - SPRING_DATASOURCE_USERNAME=userdb
      - SPRING_DATASOURCE_PASSWORD=passworddb
    depends_on:
      - db
    ports:
      - "8080:8080"
